### ISSUE TITLE
Machine-readable list of Swagger files.

### ISSUE THREAD

**Issue by IvanGoncharov** [watson-developer-cloud/watson-developer-cloud.github.io#1]
Hi,

It's really cool that you published list of SwaggerUI consoles:
https://watson-api-explorer.mybluemix.net/
But for my project I need a list of Swagger files, for now, I parse HTML as workaround.
Could please provide a link to JSON which will have links to all Swagger files?

**Comment by germanattanasio** [comment]
You can get the swagger json file if you navigate to each service and look at the networking tab. The Swagger UI is generated using the json file.

For example: https://watson-api-explorer.mybluemix.net/listings/alchemy-data-news-v1.json

**Comment by IvanGoncharov** [comment]
@germanattanasio Yes, I know this method.
Alternatively you can run `swaggerUi.options.url` in dev console.
I even wrote dedicated tool for doing that:
https://github.com/APIs-guru/swagger-scraper

I think I need to describe my use case.
It's [catalog](https://github.com/APIs-guru/api-models) of Swagger files for 200+ public APIs.
And Swagger files in my catalog regularly sync using links like:
https://watson-api-explorer.mybluemix.net/listings/alchemy-data-news-v1.json

My problem is that I want to automatically add new API or a new version of existing API.
So I need to check your page every day or write a custom script to parse HTML.

**Comment by germanattanasio** [comment]
Life is hard

**Comment by IvanGoncharov** [comment]
@germanattanasio I know :(

Another question your Swagger files missing `host` property so according to spec:

> If the host is not included, the host serving the documentation is to be used (including the port). 

So in my files, it would be `watson-api-explorer.mybluemix.net`.
I have a possibility to override it, so what is correct hostname to be used in production?

**Comment by jsstylos** [comment]
Part of the reason why json files are not explicitly exposed is that the json we use has some customization for use in the API explorer, and so are not completely accurate representations of the services themselves, and don't contain the base path, or support schemes, or authentication to match the service. You should be careful about using the Swagger definitions automatically for anything other than the API explorer they're supporting.

The correct base path is usually https://gateway.watsonplatform.net, but sometimes https://stream.watsonplatform.net and sometimes https://gateway-a.watsonplatform.net, depending on the service.

**Comment by IvanGoncharov** [comment]
@jsstylos Thank you for an answer.
I will mark them as unofficial until somebody add proper security definition and test it.
But still it's a good starting point and way better than other sources:
https://github.com/api-stack/api-stack/tree/gh-pages/data/ibm-watson

P.S. Please consider providing full Swagger spec.
It will help not only my project but entire OpenAPI ecosystem:
https://github.com/swagger-api/swagger.io/blob/wordpress//integrations/open-source.md
